// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4mJg-Hu2Xi9RK86EoFt5s6yp_kZUODX8',
    appId: '1:788530059359:web:1596ea7745c09f956323ea',
    messagingSenderId: '788530059359',
    projectId: 'mern-book-inventory-765aa',
    authDomain: 'mern-book-inventory-765aa.firebaseapp.com',
    storageBucket: 'mern-book-inventory-765aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzYrqSDLHpzV4hxxzkFD5-ZfhK-1SGPvU',
    appId: '1:788530059359:android:b4433da8e5e8f0956323ea',
    messagingSenderId: '788530059359',
    projectId: 'mern-book-inventory-765aa',
    storageBucket: 'mern-book-inventory-765aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjzw0eXqSpfxLvGqgJbqnRLGUelxKOEyg',
    appId: '1:788530059359:ios:1abae81cbdddd3626323ea',
    messagingSenderId: '788530059359',
    projectId: 'mern-book-inventory-765aa',
    storageBucket: 'mern-book-inventory-765aa.firebasestorage.app',
    iosClientId: '788530059359-26t4v9pchkoqhae0fmoc6fljskcek38v.apps.googleusercontent.com',
    iosBundleId: 'com.example.boiPabenProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjzw0eXqSpfxLvGqgJbqnRLGUelxKOEyg',
    appId: '1:788530059359:ios:1abae81cbdddd3626323ea',
    messagingSenderId: '788530059359',
    projectId: 'mern-book-inventory-765aa',
    storageBucket: 'mern-book-inventory-765aa.firebasestorage.app',
    iosClientId: '788530059359-26t4v9pchkoqhae0fmoc6fljskcek38v.apps.googleusercontent.com',
    iosBundleId: 'com.example.boiPabenProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaig87FbkRsuaZE6kEw4Gs_-buD2TzrpM',
    appId: '1:788530059359:web:b79d7052188172196323ea',
    messagingSenderId: '788530059359',
    projectId: 'mern-book-inventory-765aa',
    authDomain: 'mern-book-inventory-765aa.firebaseapp.com',
    storageBucket: 'mern-book-inventory-765aa.firebasestorage.app',
  );
}
